import { IconDefinition } from '@ant-design/icons-angular';
import {
  ApiOutline,
  ArrowDownOutline,
  ArrowRightOutline,
  ArrowUpOutline,
  BarChartOutline,
  CheckSquareOutline,
  DashboardOutline,
  FileTextOutline,
  GithubOutline,
  LockOutline,
  LoginOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MinusOutline,
  PlusOutline,
  PoweroffOutline,
  SafetyCertificateOutline,
  SlackOutline,
  SyncOutline,
  TeamOutline,
  UserOutline,
  WarningOutline,
} from '@ant-design/icons-angular/icons';

// Shared by the application and the unit-test providers so specs never miss an icon.
export const APP_ICONS: IconDefinition[] = [
  ApiOutline,
  DashboardOutline,
  FileTextOutline,
  WarningOutline,
  CheckSquareOutline,
  TeamOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  ArrowUpOutline,
  ArrowDownOutline,
  MinusOutline,
  PlusOutline,
  GithubOutline,
  LockOutline,
  SlackOutline,
  BarChartOutline,
  SyncOutline,
  UserOutline,
  SafetyCertificateOutline,
  PoweroffOutline,
  LoginOutline,
  ArrowRightOutline,
];
